services:
  - name: minix-gongu-dashboard
    type: web
    runtime: static
    buildCommand: cd review-app && npm ci && npm run build
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
